# Generated by Django 4.1.3 on 2022-11-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbatea', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customerid',
            field=models.IntegerField(blank=True, default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('delivery_address', models.CharField(max_length=300, null=True)),
                ('total_price', models.FloatField(null=True)),
                ('order_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_status', models.CharField(max_length=10, null=True)),
                ('customerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='herbatea.customer')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbatea.products')),
            ],
        ),
    ]
